from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Adding(object):
    def setupUi(self, Adding):
        Adding.setObjectName("Adding")
        Adding.resize(470, 164)
        Adding.setMinimumSize(QtCore.QSize(470, 164))
        Adding.setMaximumSize(QtCore.QSize(470, 164))
        self.name_lineedit = QtWidgets.QLineEdit(Adding)
        self.name_lineedit.setGeometry(QtCore.QRect(11, 11, 205, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name_lineedit.setFont(font)
        self.name_lineedit.setWhatsThis("")
        self.name_lineedit.setInputMask("")
        self.name_lineedit.setText("")
        self.name_lineedit.setObjectName("name_lineedit")
        self.comment_lineedit = QtWidgets.QLineEdit(Adding)
        self.comment_lineedit.setGeometry(QtCore.QRect(11, 45, 205, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comment_lineedit.setFont(font)
        self.comment_lineedit.setObjectName("comment_lineedit")
        self.path_lineedit = QtWidgets.QLineEdit(Adding)
        self.path_lineedit.setGeometry(QtCore.QRect(223, 11, 205, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.path_lineedit.setFont(font)
        self.path_lineedit.setObjectName("path_lineedit")
        self.data_lineedit = QtWidgets.QLineEdit(Adding)
        self.data_lineedit.setGeometry(QtCore.QRect(223, 45, 205, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.data_lineedit.setFont(font)
        self.data_lineedit.setObjectName("data_lineedit")
        self.cancel_button = QtWidgets.QPushButton(Adding)
        self.cancel_button.setEnabled(True)
        self.cancel_button.setGeometry(QtCore.QRect(223, 123, 93, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        self.add_button = QtWidgets.QPushButton(Adding)
        self.add_button.setEnabled(False)
        self.add_button.setGeometry(QtCore.QRect(223, 79, 117, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_button.setFont(font)
        self.add_button.setObjectName("add_button")
        self.check_button = QtWidgets.QPushButton(Adding)
        self.check_button.setGeometry(QtCore.QRect(11, 79, 93, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_button.setFont(font)
        self.check_button.setObjectName("check_button")
        self.clear_button = QtWidgets.QPushButton(Adding)
        self.clear_button.setGeometry(QtCore.QRect(11, 123, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.clear_button.setFont(font)
        self.clear_button.setObjectName("clear_button")

        self.retranslateUi(Adding)
        QtCore.QMetaObject.connectSlotsByName(Adding)

    def retranslateUi(self, Adding):
        _translate = QtCore.QCoreApplication.translate
        Adding.setWindowTitle(_translate("Adding", "Adding"))
        self.name_lineedit.setPlaceholderText(_translate("Adding", "Name"))
        self.comment_lineedit.setPlaceholderText(_translate("Adding", "Comment"))
        self.path_lineedit.setPlaceholderText(_translate("Adding", "Path"))
        self.data_lineedit.setPlaceholderText(_translate("Adding", "Data in format 12.12.2012"))
        self.cancel_button.setText(_translate("Adding", "Cancel"))
        self.add_button.setText(_translate("Adding", "Add New Art"))
        self.check_button.setText(_translate("Adding", "Сheck"))
        self.clear_button.setText(_translate("Adding", "Clear All"))
