from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ArtCatalog(object):
    def setupUi(self, ArtCatalog):
        ArtCatalog.setObjectName("ArtCatalog")
        ArtCatalog.resize(1000, 750)
        ArtCatalog.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(ArtCatalog)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setMinimumSize(QtCore.QSize(287, 151))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout.addWidget(self.listWidget, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(201, 151))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(177, 54))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        ArtCatalog.setCentralWidget(self.centralwidget)

        self.retranslateUi(ArtCatalog)
        QtCore.QMetaObject.connectSlotsByName(ArtCatalog)

    def retranslateUi(self, ArtCatalog):
        _translate = QtCore.QCoreApplication.translate
        ArtCatalog.setWindowTitle(_translate("ArtCatalog", "ArtCatalog"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("ArtCatalog", "[1]"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("ArtCatalog", "Добавить"))


class Ui_Adding(object):
    def setupUi(self, Adding):
        Adding.setObjectName("Adding")
        Adding.resize(588, 257)
        Adding.setMinimumSize(QtCore.QSize(588, 257))
        Adding.setMaximumSize(QtCore.QSize(997, 763))
        self.gridLayout_5 = QtWidgets.QGridLayout(Adding)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.name_widget = QtWidgets.QWidget(Adding)
        self.name_widget.setObjectName("name_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.name_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.name_lineedit = QtWidgets.QLineEdit(self.name_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name_lineedit.setFont(font)
        self.name_lineedit.setWhatsThis("")
        self.name_lineedit.setInputMask("")
        self.name_lineedit.setText("")
        self.name_lineedit.setObjectName("name_lineedit")
        self.gridLayout.addWidget(self.name_lineedit, 0, 0, 1, 1)
        self.name_label = QtWidgets.QLabel(self.name_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setText("")
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.name_widget, 0, 0, 1, 1)
        self.path_widget = QtWidgets.QWidget(Adding)
        self.path_widget.setObjectName("path_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.path_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.path_lineedit = QtWidgets.QLineEdit(self.path_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.path_lineedit.setFont(font)
        self.path_lineedit.setObjectName("path_lineedit")
        self.gridLayout_2.addWidget(self.path_lineedit, 0, 0, 1, 1)
        self.path_label = QtWidgets.QLabel(self.path_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.path_label.setFont(font)
        self.path_label.setText("")
        self.path_label.setObjectName("path_label")
        self.gridLayout_2.addWidget(self.path_label, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.path_widget, 0, 1, 1, 1)
        self.comment_widget = QtWidgets.QWidget(Adding)
        self.comment_widget.setObjectName("comment_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.comment_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comment_lineedit = QtWidgets.QLineEdit(self.comment_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comment_lineedit.setFont(font)
        self.comment_lineedit.setObjectName("comment_lineedit")
        self.gridLayout_3.addWidget(self.comment_lineedit, 0, 0, 1, 1)
        self.comment_label = QtWidgets.QLabel(self.comment_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comment_label.setFont(font)
        self.comment_label.setText("")
        self.comment_label.setObjectName("comment_label")
        self.gridLayout_3.addWidget(self.comment_label, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.comment_widget, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Adding)
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.data_lineedit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.data_lineedit.setFont(font)
        self.data_lineedit.setObjectName("data_lineedit")
        self.gridLayout_4.addWidget(self.data_lineedit, 0, 0, 1, 1)
        self.data_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.data_label.setFont(font)
        self.data_label.setText("")
        self.data_label.setObjectName("data_label")
        self.gridLayout_4.addWidget(self.data_label, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget, 1, 1, 1, 1)
        self.add_button = QtWidgets.QPushButton(Adding)
        self.add_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_button.setFont(font)
        self.add_button.setObjectName("add_button")
        self.gridLayout_5.addWidget(self.add_button, 2, 0, 1, 1)
        self.clear_button = QtWidgets.QPushButton(Adding)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.clear_button.setFont(font)
        self.clear_button.setObjectName("clear_button")
        self.gridLayout_5.addWidget(self.clear_button, 3, 0, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(Adding)
        self.cancel_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout_5.addWidget(self.cancel_button, 3, 1, 1, 1)
        self.label_finish = QtWidgets.QLabel(Adding)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_finish.setFont(font)
        self.label_finish.setText("")
        self.label_finish.setObjectName("label_finish")
        self.gridLayout_5.addWidget(self.label_finish, 2, 1, 1, 1)

        self.retranslateUi(Adding)
        QtCore.QMetaObject.connectSlotsByName(Adding)

    def retranslateUi(self, Adding):
        _translate = QtCore.QCoreApplication.translate
        Adding.setWindowTitle(_translate("Adding", "Adding"))
        self.name_lineedit.setPlaceholderText(_translate("Adding", "Имя"))
        self.path_lineedit.setPlaceholderText(_translate("Adding", "Путь"))
        self.comment_lineedit.setPlaceholderText(_translate("Adding", "Коментарий"))
        self.data_lineedit.setPlaceholderText(_translate("Adding", "Дата в формате дд.мм.гггг"))
        self.add_button.setText(_translate("Adding", "Добавить новый арт"))
        self.clear_button.setText(_translate("Adding", "Очистить все"))
        self.cancel_button.setText(_translate("Adding", "Отмена"))


class Ui_WatchWindow(object):
    def setupUi(self, WatchWindow):
        WatchWindow.setObjectName("WatchWindow")
        WatchWindow.resize(793, 506)
        self.gridLayout = QtWidgets.QGridLayout(WatchWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(WatchWindow)
        self.widget.setMinimumSize(QtCore.QSize(191, 81))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name_lineedit = QtWidgets.QLineEdit(self.widget)
        self.name_lineedit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_lineedit.sizePolicy().hasHeightForWidth())
        self.name_lineedit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_lineedit.setFont(font)
        self.name_lineedit.setInputMask("")
        self.name_lineedit.setText("")
        self.name_lineedit.setReadOnly(True)
        self.name_lineedit.setObjectName("name_lineedit")
        self.verticalLayout_2.addWidget(self.name_lineedit)
        self.name_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_label.setFont(font)
        self.name_label.setText("")
        self.name_label.setObjectName("name_label")
        self.verticalLayout_2.addWidget(self.name_label)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(WatchWindow)
        self.widget_2.setMinimumSize(QtCore.QSize(191, 81))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.path_lineedit = QtWidgets.QLineEdit(self.widget_2)
        self.path_lineedit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_lineedit.sizePolicy().hasHeightForWidth())
        self.path_lineedit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.path_lineedit.setFont(font)
        self.path_lineedit.setInputMask("")
        self.path_lineedit.setText("")
        self.path_lineedit.setReadOnly(True)
        self.path_lineedit.setObjectName("path_lineedit")
        self.verticalLayout_3.addWidget(self.path_lineedit)
        self.path_label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.path_label.setFont(font)
        self.path_label.setText("")
        self.path_label.setObjectName("path_label")
        self.verticalLayout_3.addWidget(self.path_label)
        self.gridLayout.addWidget(self.widget_2, 0, 1, 1, 2)
        self.widget_3 = QtWidgets.QWidget(WatchWindow)
        self.widget_3.setMinimumSize(QtCore.QSize(191, 81))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comment_lineedit = QtWidgets.QLineEdit(self.widget_3)
        self.comment_lineedit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comment_lineedit.sizePolicy().hasHeightForWidth())
        self.comment_lineedit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comment_lineedit.setFont(font)
        self.comment_lineedit.setText("")
        self.comment_lineedit.setReadOnly(True)
        self.comment_lineedit.setObjectName("comment_lineedit")
        self.verticalLayout_4.addWidget(self.comment_lineedit)
        self.comment_label = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comment_label.setFont(font)
        self.comment_label.setText("")
        self.comment_label.setObjectName("comment_label")
        self.verticalLayout_4.addWidget(self.comment_label)
        self.gridLayout.addWidget(self.widget_3, 1, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(WatchWindow)
        self.widget_4.setMinimumSize(QtCore.QSize(191, 81))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.data_lineedit = QtWidgets.QLineEdit(self.widget_4)
        self.data_lineedit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_lineedit.sizePolicy().hasHeightForWidth())
        self.data_lineedit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.data_lineedit.setFont(font)
        self.data_lineedit.setText("")
        self.data_lineedit.setReadOnly(True)
        self.data_lineedit.setObjectName("data_lineedit")
        self.verticalLayout_5.addWidget(self.data_lineedit)
        self.data_window = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.data_window.setFont(font)
        self.data_window.setText("")
        self.data_window.setObjectName("data_window")
        self.verticalLayout_5.addWidget(self.data_window)
        self.gridLayout.addWidget(self.widget_4, 1, 1, 1, 2)
        self.art_label = QtWidgets.QLabel(WatchWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.art_label.sizePolicy().hasHeightForWidth())
        self.art_label.setSizePolicy(sizePolicy)
        self.art_label.setMinimumSize(QtCore.QSize(771, 271))
        self.art_label.setText("")
        self.art_label.setObjectName("art_label")
        self.gridLayout.addWidget(self.art_label, 2, 0, 1, 3)
        self.edit_pushbutton = QtWidgets.QPushButton(WatchWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edit_pushbutton.setFont(font)
        self.edit_pushbutton.setObjectName("edit_pushbutton")
        self.gridLayout.addWidget(self.edit_pushbutton, 3, 0, 1, 1)
        self.save_pushButton = QtWidgets.QPushButton(WatchWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_pushButton.setFont(font)
        self.save_pushButton.setObjectName("save_pushButton")
        self.gridLayout.addWidget(self.save_pushButton, 3, 1, 1, 1)
        self.delete_pushbutton = QtWidgets.QPushButton(WatchWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_pushbutton.setFont(font)
        self.delete_pushbutton.setObjectName("delete_pushbutton")
        self.gridLayout.addWidget(self.delete_pushbutton, 3, 2, 1, 1)

        self.retranslateUi(WatchWindow)
        QtCore.QMetaObject.connectSlotsByName(WatchWindow)

    def retranslateUi(self, WatchWindow):
        _translate = QtCore.QCoreApplication.translate
        WatchWindow.setWindowTitle(_translate("WatchWindow", "Watch"))
        self.name_lineedit.setPlaceholderText(_translate("WatchWindow", "Имя"))
        self.path_lineedit.setPlaceholderText(_translate("WatchWindow", "Путь"))
        self.comment_lineedit.setPlaceholderText(_translate("WatchWindow", "Комментарий"))
        self.data_lineedit.setPlaceholderText(_translate("WatchWindow", "Дата"))
        self.edit_pushbutton.setText(_translate("WatchWindow", "Изменить"))
        self.save_pushButton.setText(_translate("WatchWindow", "Сохранить"))
        self.delete_pushbutton.setText(_translate("WatchWindow", "Удалить"))
