from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WatchWindow(object):
    def setupUi(self, WatchWindow):
        WatchWindow.setObjectName("WatchWindow")
        WatchWindow.resize(793, 506)
        self.gridLayout = QtWidgets.QGridLayout(WatchWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(WatchWindow)
        self.widget.setMinimumSize(QtCore.QSize(191, 81))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name_lineedit = QtWidgets.QLineEdit(self.widget)
        self.name_lineedit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_lineedit.sizePolicy().hasHeightForWidth())
        self.name_lineedit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_lineedit.setFont(font)
        self.name_lineedit.setReadOnly(True)
        self.name_lineedit.setObjectName("name_lineedit")
        self.verticalLayout_2.addWidget(self.name_lineedit)
        self.name_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_label.setFont(font)
        self.name_label.setText("")
        self.name_label.setObjectName("name_label")
        self.verticalLayout_2.addWidget(self.name_label)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 2)
        self.widget_2 = QtWidgets.QWidget(WatchWindow)
        self.widget_2.setMinimumSize(QtCore.QSize(191, 81))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.path_lineedit = QtWidgets.QLineEdit(self.widget_2)
        self.path_lineedit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_lineedit.sizePolicy().hasHeightForWidth())
        self.path_lineedit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.path_lineedit.setFont(font)
        self.path_lineedit.setReadOnly(True)
        self.path_lineedit.setObjectName("path_lineedit")
        self.verticalLayout_3.addWidget(self.path_lineedit)
        self.path_label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.path_label.setFont(font)
        self.path_label.setText("")
        self.path_label.setObjectName("path_label")
        self.verticalLayout_3.addWidget(self.path_label)
        self.gridLayout.addWidget(self.widget_2, 0, 2, 1, 2)
        self.widget_3 = QtWidgets.QWidget(WatchWindow)
        self.widget_3.setMinimumSize(QtCore.QSize(191, 81))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comment_lineedit = QtWidgets.QLineEdit(self.widget_3)
        self.comment_lineedit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comment_lineedit.sizePolicy().hasHeightForWidth())
        self.comment_lineedit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comment_lineedit.setFont(font)
        self.comment_lineedit.setReadOnly(True)
        self.comment_lineedit.setObjectName("comment_lineedit")
        self.verticalLayout_4.addWidget(self.comment_lineedit)
        self.comment_label = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comment_label.setFont(font)
        self.comment_label.setText("")
        self.comment_label.setObjectName("comment_label")
        self.verticalLayout_4.addWidget(self.comment_label)
        self.gridLayout.addWidget(self.widget_3, 1, 0, 2, 2)
        self.art_label = QtWidgets.QLabel(WatchWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.art_label.sizePolicy().hasHeightForWidth())
        self.art_label.setSizePolicy(sizePolicy)
        self.art_label.setMinimumSize(QtCore.QSize(771, 271))
        self.art_label.setText("")
        self.art_label.setObjectName("art_label")
        self.gridLayout.addWidget(self.art_label, 3, 0, 1, 4)
        self.widget_4 = QtWidgets.QWidget(WatchWindow)
        self.widget_4.setMinimumSize(QtCore.QSize(191, 81))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.data_lineedit = QtWidgets.QLineEdit(self.widget_4)
        self.data_lineedit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_lineedit.sizePolicy().hasHeightForWidth())
        self.data_lineedit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.data_lineedit.setFont(font)
        self.data_lineedit.setReadOnly(True)
        self.data_lineedit.setObjectName("data_lineedit")
        self.verticalLayout_5.addWidget(self.data_lineedit)
        self.data_window = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.data_window.setFont(font)
        self.data_window.setText("")
        self.data_window.setObjectName("data_window")
        self.verticalLayout_5.addWidget(self.data_window)
        self.gridLayout.addWidget(self.widget_4, 1, 2, 1, 2)
        self.save_pushButton = QtWidgets.QPushButton(WatchWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_pushButton.setFont(font)
        self.save_pushButton.setObjectName("save_pushButton")
        self.gridLayout.addWidget(self.save_pushButton, 5, 2, 1, 2)
        self.edit_pushbutton = QtWidgets.QPushButton(WatchWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edit_pushbutton.setFont(font)
        self.edit_pushbutton.setObjectName("edit_pushbutton")
        self.gridLayout.addWidget(self.edit_pushbutton, 5, 0, 1, 2)

        self.retranslateUi(WatchWindow)
        QtCore.QMetaObject.connectSlotsByName(WatchWindow)

    def retranslateUi(self, WatchWindow):
        _translate = QtCore.QCoreApplication.translate
        WatchWindow.setWindowTitle(_translate("WatchWindow", "Watch"))
        self.name_lineedit.setText(_translate("WatchWindow", "Name"))
        self.path_lineedit.setText(_translate("WatchWindow", "Path"))
        self.comment_lineedit.setText(_translate("WatchWindow", "Comment"))
        self.data_lineedit.setText(_translate("WatchWindow", "Data"))
        self.save_pushButton.setText(_translate("WatchWindow", "Save"))
        self.edit_pushbutton.setText(_translate("WatchWindow", "Edit"))
